

@startuml

abstract class GenericVertex

abstract class NamedVertex extends GenericVertex implements Serializable {
    -String name;
    -String description;

    +NamedVertex(String name, String description)

    +String getName()
    +String getDescription()
    +void isValid(final Graph<NamedVertex> graph) throws ValidationException
    +void isFullyValid(final Graph<NamedVertex> graph) throws ValidationException
    +boolean isDefinedType()
    +String toString()
    +{abstract} boolean isOfType(MatType type)
    +{abstract} MatType getType();
}

@enduml
