
@startuml

interface ProofNetworkRepository {
     void addVertex(NamedVertex vertex)
     boolean addEdge(NamedVertex fromVertex, NamedVertex toVertex)
     void removeVertex(NamedVertex vertex)
     boolean removeEdgeIfExists(int fromId, int toId)
     List<NamedVertex> getVertices()
     NamedVertex getVertexById(int vertexId)
     Graph<NamedVertex> getGraph()
     ValidationExceptionHandler getExceptionHandler()
     boolean fullValidation();
}

@enduml